services:
  config-service:
    build: ./config-service
    ports:
      - "8888:8888"

  discovery-service:
    build:
      context: discovery-service1
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  gateway-service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - discovery-service


  order-service:
    build:
      context: order-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - config-service
      - discovery-service
